### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by PeterNV** [PeterNV/-GCMS-Pedro-VilaNova#2]
@PeterNV 
@ramidedantas
- [x] **1.Instalar Git localmente:tada:**

- [x] **2.Criar projeto local:tada:**
- [x] **3.Criar repositório local e realizar commits:tada:**

- [x] **4.Subir alterações para o repositório remoto:tada:**
- [x] **5.Fazer alterações no repositório da turma:tada:**
